### ISSUE TITLE
Vector de parejas en parte privada de Jugador

### ISSUE THREAD

**Issue by andresfeliper3** [andresfeliper3/ipoo_project#2]
¿Para qué usar un vector de parejas en la parte privada de Jugador?
vector <pair <Individuo*, string letraParaMover>> individuos;

¿No sería mejor que letreaParaMover fuera un atributo de Individuo?

**Comment by DavidHernandezUV** [comment]
Yo creo que Diego lo hizo así para que el jugador pueda meter individuos nuevos y asignarle una letra de preferencia para poder moverla, esto con el propósito de que el juego no quede tan limitado. No sé si me equivoco a lo que creo que pensó Diego.

**Comment by DiegoFLM** [comment]
La idea también es buscar la eficiencia. Si letra para mover es un atributo
de individuo, al recibir una letra, jugador tiene que ir a cada individuo y
preguntarle cuál es su letra, mientras que con un vector de parejas puede
tener todo a la mano y hacer esa búsqueda de forma más rápida.
Otra cosa es que Barca también tendría que tener ese atributo y un método
para decir qué letra tiene asignada. Pero se puede hacer de ambas formas, y
en el doc que habíamos hecho no aclaramos eso. ¿Porqué sería mejor si
individuo tiene ese atributo?

**Comment by DiegoFLM** [comment]
Aunque acabo de darme cuenta de que sería mucho más simple si individuo
tiene ese atributo, y jugador no le pregunta a cada uno, sino que le envía
a todos los individuos la letra que recibió, y cada individuo y la barca
revisan si les toca moverse y actúan.

**Comment by andresfeliper3** [comment]
Eso último que djio Diego me parece lo más razonable
